---
id: "..-..-..-..-..-tmp-aiktest-SOUL"
title: "SOUL"
category: "identity"
tags: ["soul"]
type: "identity"
source: "../../../../../tmp/aiktest/SOUL.md"
indexed_at: "2026-07-09T11:58:07.809Z"
updated_at: "2026-07-09T11:56:38.162Z"
---

SOUL
