---
id: "..-..-..-..-..-tmp-aiktest-c"
title: "c"
category: "test"
tags: ["c"]
type: "test"
source: "../../../../../tmp/aiktest/c.json"
indexed_at: "2026-07-09T11:58:07.838Z"
updated_at: "2026-07-09T11:56:38.162Z"
---

{}
