---
id: "..-..-..-..-..-tmp-aiktest2-docs-arch"
title: "arch"
category: "documentation"
tags: ["arch"]
type: "documentation"
source: "../../../../../tmp/aiktest2/docs/arch.md"
indexed_at: "2026-07-09T11:58:24.782Z"
updated_at: "2026-07-09T11:58:23.753Z"
---

See [[readme]] and the [guide](docs/guide.md). Also http://example.com/x
